# Generated by Django 3.2.5 on 2021-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_price', models.FloatField(default=0.0)),
                ('p_disc', models.TextField()),
                ('p_img', models.ImageField(upload_to='pics')),
                ('p_cat', models.CharField(choices=[('fashion', 'fashion'), ('electronics', 'electronics'), ('accessories', 'accessories')], max_length=100)),
            ],
        ),
    ]
