# Generated by Django 3.2.5 on 2021-07-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_specification',
            field=models.CharField(default='pant', max_length=100),
        ),
    ]
