# Generated by Django 3.2.5 on 2021-07-13 09:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_history',
            name='searched_on',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 9, 9, 15, 349676, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart_on', models.DateField(default=datetime.datetime(2021, 7, 13, 9, 9, 15, 350273, tzinfo=utc))),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
